"""empty message

Revision ID: 46a0b037eeee
Revises: e90a3dd11019
Create Date: 2025-01-10 12:48:44.941909

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '46a0b037eeee'
down_revision = 'e90a3dd11019'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Name', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('Name')
    )
    op.create_table('time_slot',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('StartTime', sa.DateTime(), nullable=False),
    sa.Column('EndTime', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('time_slot', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_time_slot_EndTime'), ['EndTime'], unique=False)
        batch_op.create_index(batch_op.f('ix_time_slot_StartTime'), ['StartTime'], unique=False)

    op.create_table('whish_list',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first', sa.Integer(), nullable=False),
    sa.Column('second', sa.Integer(), nullable=False),
    sa.Column('third', sa.Integer(), nullable=False),
    sa.Column('fourth', sa.Integer(), nullable=False),
    sa.Column('fifth', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['fifth'], ['jobs.id'], ),
    sa.ForeignKeyConstraint(['first'], ['jobs.id'], ),
    sa.ForeignKeyConstraint(['fourth'], ['jobs.id'], ),
    sa.ForeignKeyConstraint(['id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['second'], ['jobs.id'], ),
    sa.ForeignKeyConstraint(['third'], ['jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('student',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timeSlot', sa.Integer(), nullable=False),
    sa.Column('whish', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['timeSlot'], ['time_slot.id'], ),
    sa.ForeignKeyConstraint(['whish'], ['whish_list.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('student')
    op.drop_table('whish_list')
    with op.batch_alter_table('time_slot', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_time_slot_StartTime'))
        batch_op.drop_index(batch_op.f('ix_time_slot_EndTime'))

    op.drop_table('time_slot')
    op.drop_table('jobs')
    # ### end Alembic commands ###
